### PR TITLE
Verify Mattermost for 2021

### PR DESCRIPTION
**Pull request by donno2048**

### CODE REVIEW

**Review by SoftCreatR — CHANGES_REQUESTED** [review]
Please remove unnecessary line breaks.

**Comment by donno2048** [comment]
I just copied the example file from the CONTRIBUTING.md, the line breaks came from there

**Comment by SoftCreatR** [comment]
Like you said: That's just an example :) The easiest would have been to just move the file from the `2020` directory and change it's contents accordingly.

**Comment by ulgens** [comment]
I can't see why you are moving files away from 2020 instead of copying them. Why not just keep 2020 as is?

**Comment by SoftCreatR** [comment]
To prevent duplicates. No one likes duplicates.

😸

**Comment by ulgens** [comment]
Why would there be duplicates between different folders?

**Comment by SoftCreatR** [comment]
Why is this even a problem? We just decided to keep the repo as clean as possible., that's all :)

**Pull request merged**
