### PR TITLE
Added Adobe Swag Opportunity

### PR DESCRIPTION
**Pull request by Aman-am**

### CODE REVIEW

**Comment by crweiner** [comment]
Hay there @Aman-am! The Adobe participation in Hacktoberfest is currently listed under Magento with the same "Squashtoberfest" blog link. Perhaps we should change that to "Magento/Adobe" or something similar to make it more clear? What are your thoughts on that?

**Comment by Aman-am** [comment]
Hey,

Oh, I missed that. Sure we can do that and I found a couple of more
opportunities, will add them as well.

Thanks!

**Comment by benbarth** [comment]
If you remove the new entry and edit the existing Magento entry to "Magento / Adobe" we'll accept this PR.

**Comment by Aman-am** [comment]
Hey Benbarth,

I've made the respective changes. 

Thanks

**Comment by crweiner** [comment]
Thank you very much! Have a wonderful Hacktoberfest! :+1:

**Pull request merged**
