### PR TITLE
Verified Parity with 2019 

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Added Parity to the list, Earlier PR got some error

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
Now there is no conflict

**Comment by crweiner** [comment]
As @benbarth already pointed out [here](https://github.com/benbarth/hacktoberfest-swag/pull/64#issuecomment-537126461) and [here](https://github.com/benbarth/hacktoberfest-swag/pull/64#issuecomment-537127602) there is already a swag bag icon he'd prefer you to use. Please stick to the [/icons/](https://github.com/benbarth/hacktoberfest-swag/tree/master/icons) folder. This PR still has you uploading ```shopping-bag.png```. 

Please take the time to choose 1 PR (preferably this one) that has everything fully aligned with the existing formatting of the rest of the repo and follow the instructions provided by the repo maintainers.

**Comment by Ishaan28malik** [comment]
@crweiner I have made the final changes in the last update with `swag.png`. Can you please check this and see if anything else required and I can proceed with further contributions.

**Comment by benbarth** [comment]
Hi @Ishaan28malik, your PR still has the shopping-bag.png. Could you remove it?

**Pull request merged**
