### PR TITLE
Added LoginRadius Swags

### PR DESCRIPTION
**Pull request by ashish8947**
- [x] I've read the [Contributing.md](../blob/master/CONTRIBUTING.md) file
- [x] I do not intend to make low-value changes, just for swag. I am aware, that my PR could otherwise be flagged as `spam` or `invalid` and may lead to a permanent exclusion from the Hacktoberfest event.

### Adding a new Hacktoberfest participant

- [x] I did not edit the README.md file by hand
- [x] I made sure, that the new participant has not already been added
- [x] I'm not adding a company from the [blocklist](../blob/master/.gitignore)

### Editing an existing Hacktoberfest participant

- [x] I did not edit the README.md file by hand
- [x] I made proper changes to the existing participant.yml file

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Please just edit the existing file.

**Review by SoftCreatR — CHANGES_REQUESTED** [review]
Please just edit the existing file.

**Comment by ashish8947** [comment]
@SoftCreatR 
What should I edit in the same? Can you explain it a bit more?

**Comment by SoftCreatR** [comment]
> @SoftCreatR
> What should I edit in the same? Can you explain it a bit more?

A file named loginradius.yml already exists. Just edit that one, rather than creating a new one under a different name.

**Review by SoftCreatR — APPROVED** [review]

**Pull request merged**
