### PR TITLE
issue #2: Added awesome_bot and build passing badge in README.md

### LINKED ISSUE #2: Add awesome_bot to verify README.md links
Like https://github.com/benbarth/essential-apps/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by nityanandagohain**
fixes #2

### CODE REVIEW

**Comment by benbarth** [comment]
Hi Nityananda,
These changes are great; however, the badge should be for Travis Ci not Buildkite. An example can be found at https://github.com/benbarth/essential-apps. After changing the badge, please verify that the build runs successfully.

**Comment by nityanandagohain** [comment]
I have done the changes, is it okay?

**Comment by nityanandagohain** [comment]
@benbarth please help me with the issues.

**Comment by benbarth** [comment]
Sure, I can help. I'll be available in a few hours. I'll add more detail as to why the build is failing.

**Comment by benbarth** [comment]
Clicking the build failed details takes you to: https://travis-ci.org/benbarth/hacktoberfest-swag/builds/435608182

There you can see four issues :-(

```
> Links 
  1. [L07] 301 https://travis-ci.org/benbarth/hacktoberfest-swag.svg?branch=master  → https://api.travis-ci.org/benbarth/hacktoberfest-swag.svg?branch=master 
  2. [L24] 302 https://blog.hasura.io/announcing-hacktoberfest-2018-with-hasura-621045dc9560  → https://medium.com/m/global-identity?redirectUrl=https%3A%2F%2Fblog.hasura.io%2Fannouncing-hacktoberfest-2018-with-hasura-621045dc9560 
  3. [L25] 301 https://aka.ms/hacktoberfest  → https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/?WT.mc_id=hacktoberfest-none-beverst 
> Dupes 
  1. [L14] https://hacktoberfest.digitalocean.com/
```

For the links: The errors are because of a redirects. These can be solved by adding `--allow-redirect` to the awesome_bot command.
For the dupes: It should be added to a whitelist by adding `--white-list https://hacktoberfest.digitalocean.com/`.

The awesome_bot documentation can be found here: https://github.com/dkhamsing/awesome_bot

**Comment by nityanandagohain** [comment]
Thanks, @benbarth  I have made the required changes and now the build is passing.

**Comment by benbarth** [comment]
Looks good! Merging...

**Pull request merged**
