### PR TITLE
Create qmk.yml

### PR DESCRIPTION
**Pull request by sanket-bhatt**
QMK Hacktoberfest Details Addition

### CODE REVIEW

**Comment by SoftCreatR** [comment]
The swag item needs to be `shirt`

Furthermore, it might be easier for you to move the existing qmk.yml from the 2019 directory to the 2020 directory.

**Comment by SoftCreatR** [comment]
@sanket-bhatt Could you please remove the file qmk.yml from the 2019 directory?

**Review by SoftCreatR — CHANGES_REQUESTED** [review]
Could you please remove the file qmk.yml from the 2019 directory?

**Comment by benbarth** [comment]
That repo was last updated in 2019. I don't see anything to indicate that they are participating in 2020. 😞

**Comment by SoftCreatR** [comment]
That being said, I'll close this PR. Thank you for your contribution, anyways.

**Pull request closed without merging**
