### PR TITLE
Replace Travis with GitHub Actions

### PR DESCRIPTION
**Pull request by SoftCreatR**

### CODE REVIEW

**Comment by benbarth** [comment]
I love it!

**Comment by SoftCreatR** [comment]
I'm a big fan of GitHub actions  :octocat:

**Comment by benbarth** [comment]
Do you have any creative ideas to improve or simplify the workflow for contributors?

**Comment by SoftCreatR** [comment]
When building the actions, I was already thinking about possible optimizations.

First of all, I would create branches for recent years and remove everything in the master (current year) that isn't verified.

Then, one possible optimization could be to have a separate file for every participant, like this:

```yml
---
Name: Acme Corporation
Website: https://acme.corp
Swag:
  - stickers
  - shirt
Description: "Create one or more merged pull requests."
Details: https://acme.corp/blog/acme-hacktoberfest-2020/
```

After a small validation, another job adds this to the README in the correct order, so there won't be any need to edit the readme in order to add new participants.

Updating the README is pretty simple. All you need is to mark the area, where links will be inserted, e.g.

```
<!-- start list -->
<!-- end list -->
```

and the job will execute a script, that iterates over all yml files and generates the table.

**Comment by benbarth** [comment]
**I love the idea to automatically generate the README!**

What I've been doing is keeping the previous year's entries until a week or so into hacktoberfest. Last year some teams announced swag during hacktoberfest and it was good that the item wasn't removed. I think this works well.

**Comment by SoftCreatR** [comment]
> it was good that the item wasn't removed

Well, the plan isn't to remove anything. The plan is to keep the current year's README clean from obsolete entries. By creating branches or releases for every year, nothing will be lost.

**Comment by benbarth** [comment]
> > it was good that the item wasn't removed
> 
> Well, the plan isn't to remove anything. The plan is to keep the current year's README clean from obsolete entries. By creating branches or releases for every year, nothing will be lost.

True. My main concern is that some users only visit [the website](https://benbarth.github.io/hacktoberfest-swag/) and it would be good to have the unverified items. Perhaps there are two tables. The first with verified items, and the second with unverified.

> > I love the idea to automatically generate the README!
> 
> I'll try to build something.

🎉 💯 🚀

**Comment by SoftCreatR** [comment]
> True. My main concern is that some users only visit the website and it would be good to have the unverified items. Perhaps there are two tables. The first with verified items, and the second with unverified.

Had the same idea. However, I would put it in a "spoiler", so people can expand it, so the focus will stay on the verified ones.

**Comment by SoftCreatR** [comment]
@benbarth There you go: https://github.com/SoftCreatR/hacktoberfest-swag/tree/auto-readme

I'll create a PR tomorrow ;)

**Comment by benbarth** [comment]
I love it!

**Comment by SoftCreatR** [comment]
Well, there's more. I'm currently trying to make everything more generic so that there's no need to update everything by hand, every year. To accomplish this, there will be a placeholder for the current year, that is being filled upon the action execution.

I've even replaced the logo with a more generic one:

hacktoberfest-logo

The new structure uses year numbers, so everything within the directory `2020` will be listed as verified, all others will be listed as unverified/past participants.

The corresponding action will be automatically executed on Jan 01 of every year at 0.00 UTC, so you'll have a fresh README every year, without the need of manually changing anything ;)

**Pull request merged**
