### PR TITLE
add LadybugTools

### LINKED ISSUE #75: Add Ladybug Tools
Refer to their announcement: https://discourse.ladybug.tools/t/celebrate-hacktoberfest-2019-with-ladybug-tools/7314.

> In addition to the Hacktoberfest swag, LadybugTools is offering a sticker if you contribute 1 or more Pull Requests to solve one of our hacktoberfest labelled issues.

### PR DESCRIPTION
**Pull request by tasawernawaz**
Fixes #75

### CODE REVIEW

**Comment by benbarth** [comment]
Hi @tasawernawaz, thank you for taking the time to create a PR! This PR is failing validation for the same reason as #78. (The list is no longer in alphabetical order.) If you correct the order I'd be happy to merge this PR.

**Comment by tasawernawaz** [comment]
@benbarth fix failing tests

**Comment by benbarth** [comment]
I think LadyBug should be before LBRY. I'll fix the build validation script.

**Comment by tasawernawaz** [comment]
> Whoops! You removed the 2019 updates.

Sorry, that was a typo. I have moved Ladybug before LBRY.

**Pull request merged**
