### PR TITLE
css

### PR DESCRIPTION
**Pull request by Nonim01**
- [x] I've read the [Contributing.md](../blob/master/CONTRIBUTING.md) file
- [x] I do not intend to make low-value changes, just for swag. I am aware, that my PR could otherwise be flagged as `spam` or `invalid` and may lead to a permanent exclusion from the Hacktoberfest event.

### Adding a new Hacktoberfest participant

- [x] I did not edit the README.md file by hand
- [x] I made sure, that the new participant has not already been added
- [x] I'm not adding a company from the [blocklist](../blob/master/.gitignore)

### Editing an existing Hacktoberfest participant

- [x] I did not edit the README.md file by hand
- [x] I made proper changes to the existing participant.yml file

### CODE REVIEW

**Comment by Nonim01** [comment]
css

**Comment by Nonim01** [comment]
css

**Comment by SoftCreatR** [comment]
Would you mind explaining your changes?

**Comment by crweiner** [comment]
Hi @Nonim01, PRs like this (which are clearly spam) are the reason why [Hacktoberfest has changed the rules.](https://hacktoberfest.digitalocean.com/hacktoberfest-update) PRs must now be merged or labeled properly in order to count, so submitting things like this isn't going to help you anymore. I encourage you to submit meaningful contributions to the projects you know and love and take this time to learn a new skill.

@SoftCreatR, see [here](https://github.com/mdn/beginner-html-site-styled/pull/42), [here](https://github.com/DSCFutminna/hacktoberfest-html/pull/16), [here](https://github.com/mdn/beginner-html-site-scripted/pull/20), and [here](https://github.com/tushan1/new-test/pull/1) for his other attempts to game the system.

**Pull request closed without merging**
