### PR TITLE
Added Bagisto as a Participant.

### PR DESCRIPTION
**Pull request by rahulsunil2**
- [x] I have read and understand the [Contributing.md](../blob/master/CONTRIBUTING.md) guidelines
- [x] I do not intend to make low-value changes, just for swag. I am aware that my PR could otherwise be flagged as `spam` or `invalid` and may lead to permanent exclusion from the Hacktoberfest event.

### Adding a new Hacktoberfest participant

- [x] I did not edit the README.md file by hand
- [x] I have checked to ensure the new participant is not a duplicate and has not already been added
- [x] I am not adding a company from the [blocklist](../blob/master/.gitignore)
- [x] I have added the participant according to the [Contributing.md](../blob/master/CONTRIBUTING.md) guidelines

### Updating an existing Hacktoberfest participant

- [ ] I did not edit the README.md file by hand
- [ ] I have updated the existing participant.yml file according to the [Contributing.md](../blob/master/CONTRIBUTING.md) guidelines

### Removing a participant
- [ ] I did not edit the README.md file by hand
- [ ] I have checked to ensure the participant is not participating this year
- [ ] I have provided evidence that the participant is not participating this year

### Updating the README.md

- [ ] I have discussed the proposed changes and received approval from a maintainer (@benbarth, @SoftCreatR, or @crweiner)

### CODE REVIEW

**Comment by rahulsunil2** [comment]
@SoftCreatR Can you please review this PR as well.

**Comment by SoftCreatR** [comment]
I'm not sure about this one. From what I can see, in order to get swags besides the normal hacktoberfest ones, you have to attend at their live event, don't you?

**Comment by rahulsunil2** [comment]
image


> I'm not sure about this one. From what I can see, in order to get swags besides the normal hacktoberfest ones, you have to attend at their live event, don't you?

No, we have to register in Bagisto and have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest

Also, For every 4 PR that gets accepted, you can adopt Baggy The Elephant along with cool swags.

**Comment by SoftCreatR** [comment]
The screenshot refers to the original hacktoberfest.

**Pull request closed without merging**
