### PR TITLE
corrections in readme like spelling

### PR DESCRIPTION
**Pull request by jatin-code21**

### CODE REVIEW

**Comment by SoftCreatR** [comment]
@benbarth

**Comment by benbarth** [comment]
Hi @jatin-code21, please discuss changes to the README with a maintainer before making a PR. More details can be found in our contributing guide. I'll accept the change from incentivise to incentivize. The other changes aren't necessary. The label case doesn't really matter but labels are typically lowercase. The most common format of "open source" has no dash [as discussed on the Wikipedia page](https://en.wikipedia.org/wiki/Talk:Open-source_software#Requested_move_13_October_2022).

**Comment by jatin-code21** [comment]
Please can you guide me on where to discuss the changes to be made? 

If it is here only then, I want to make a PR for changing the incentivise to incentivize in the readme.md.
Thank You.

**Comment by vimode** [comment]
@jatin-code21 Its generally a good idea to first open an issue to discuss this way you only work on whats approved.

**Pull request merged**
