### PR TITLE
Added Activeloop,DXHEROES in Do list

### PR DESCRIPTION
**Pull request by drraghavendra**
- [ ] I've read the [Contributing.md](../blob/master/CONTRIBUTING.md) file
- [ ] I do not intend to make low-value changes, just for swag. I am aware, that my PR could otherwise be flagged as `spam` or `invalid` and may lead to a permanent exclusion from the Hacktoberfest event.

### Adding a new Hacktoberfest participant

- [ ] I did not edit the README.md file by hand
- [ ] I made sure, that the new participant has not already been added
- [ ] I'm not adding a company from the [blocklist](../blob/master/.gitignore)

### Editing an existing Hacktoberfest participant

- [ ] I did not edit the README.md file by hand
- [ ] I made proper changes to the existing participant.yml file

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Please read the [Contribution guidelines](https://github.com/benbarth/hacktoberfest-swag/blob/master/CONTRIBUTING.md) and update your PR accordingly.

**Comment by drraghavendra** [comment]
activeloop.yml,dxheroes.yml files uploaded

**Comment by drraghavendra** [comment]
please review and approve

**Comment by SoftCreatR** [comment]
Still invalid.

**Comment by SoftCreatR** [comment]
Nope...

**Comment by drraghavendra** [comment]
please wait iam completing

**Comment by drraghavendra** [comment]
changes made as per your inference in readme.md file

**Comment by SoftCreatR** [comment]
Well, that's not what is written in the contribution guidelines.

**Comment by SoftCreatR** [comment]
Still wrong 🤯

**Comment by drraghavendra** [comment]
can you suggest me where i have gone wrong

**Comment by SoftCreatR** [comment]
https://github.com/benbarth/hacktoberfest-swag/blob/master/CONTRIBUTING.md

**Comment by SoftCreatR** [comment]
I've added DX Heroes & Activeloop by myself. However, since you were trying your best to contribute, I've added the "hacktoberfest-accepted" label, even if I did not merge your PR.

**Pull request closed without merging**
