### PR TITLE
Verified Parity for 2019

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Parity is a foundation of blockchain innovators and they have introduced Hacktoberfest Gym bag for this year ( @Hacktoberfest2019 )

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@benbarth Please have a look.

**Comment by benbarth** [comment]
@Ishaan28malik Did you create that image? The image must be licensed appropriately.

**Comment by benbarth** [comment]
We already have a "swag bag" icon.   Swag

**Comment by Ishaan28malik** [comment]
Ok let me update it, thanks

**Comment by crweiner** [comment]
New PR Opened #68 replacing this one.

**Pull request closed without merging**
