### PR TITLE
edit year

### PR DESCRIPTION
**Pull request by d-schaffer**
2020 to 2021

- [x] I've read the [Contributing.md](../blob/master/CONTRIBUTING.md) file
- [x] I do not intend to make low-value changes, just for swag. I am aware, that my PR could otherwise be flagged as `spam` or `invalid` and may lead to a permanent exclusion from the Hacktoberfest event.

### Adding a new Hacktoberfest participant

- [x] I did not edit the README.md file by hand
- [x] I made sure, that the new participant has not already been added
- [ ] I'm not adding a company from the [blocklist](../blob/master/.gitignore)

### Editing an existing Hacktoberfest participant

- [ ] I did not edit the README.md file by hand
- [ ] I made proper changes to the existing participant.yml file

### CODE REVIEW

**Comment by donno2048** [comment]
**If** they participate this year too move it to the 2021 directory and change the URL...

**Comment by d-schaffer** [comment]
@donno2048  are they even participating this year?
I don't know, I was just under the assumption that they would.
Because it was here on the site, thought that's just a typo.
But of course you're right that should be moved correctly then

**Comment by SoftCreatR** [comment]
See my link

**Comment by donno2048** [comment]
> @donno2048 are they even participating this year?

Actually, they are https://www.loginradius.com/open-source/

**Comment by d-schaffer** [comment]
good, i will fix this later today.

**Comment by d-schaffer** [comment]
okay not intressted to do this.
time waste
someone else should do this PR :)

**Pull request closed without merging**
